name: Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Change this if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@your-ec2-ip << 'EOF'
            cd /home/ec2-user/pixel-portfolio-engine
            git pull origin main
            npm install
            npm run build
            sudo systemctl restart nginx
          EOF
