name: Deploy React Vite App to AWS EC2

on:
  push:
    branches:
      - main  # Adjust if deploying from a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/id_rsa

      - name: Test SSH Connection
        run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} "echo 'SSH connection successful'"

      - name: Deploy with PM2
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
          cd /home/ec2-user/pixel-portfolio-engine  # Change to your project path
          
          # Pull latest changes
          git pull origin main
          
          # Install dependencies
          npm install --production
          
          # Build the project (Only on EC2)
          npm run build

          # Restart with PM2
          pm2 stop pixel-portfolio || true  # Stop existing process if running
          pm2 start npm --name "pixel-portfolio" -- run preview  # Start Vite preview mode with PM2
          
          # Save PM2 process list
          pm2 save
          
          exit
          EOF
